#_______       _           _    _      _                        _____ _
#|__   __|     | |         | |  | |    (_)                      / ____| |
#| | ___  __| | ___  ___| | _| |     _ _ __ ___  _ __   __ _| |    | |__   __ _  ___
#| |/ _ \/ _` |/ _ \/ __| |/ / |    | | '_ ` _ \| '_ \ / _` | |    | '_ \ / _` |/ _ \
#| |  __/ (_| |  __/\__ \   <| |____| | | | | | | |_) | (_| | |____| | | | (_| | (_) |
#|_|\___|\__,_|\___||___/_|\_\______|_|_| |_| |_| .__/ \__,_|\_____|_| |_|\__,_|\___/

# Autor: Tedesk
# Esse arquivo foi criado com a 1.8.8 em mente.
# Por favor, mude os sons e efeitos desse arquivo considerando a versão de seu servidor.

mundos-imunes:
  - 'mundo2'
tempo:
  total: 300
  avisos:
    - 180
    - 60
perms:
  admin: "tlc.admin"
tipo: #Disponíveis: ACTIONBAR, TITLE, CHAT
  aviso:
    - 'ACTIONBAR'
    - 'CHAT'
  contagem:
    - 'ACTIONBAR'
  limpo:
    - 'ACTIONBAR'
    - 'CHAT'
sons:
  tipo:
    aviso: NOTE_BASS
    contagem: NOTE_STICKS
    limpo: NOTE_PLING
  volume:
    aviso: 1.0
    contagem: 1.0
    limpo: 1.0
  pitch:
    aviso: 1.0
    contagem: 1.0
    limpo: 1.0
efeitos:
  tipo: SMOKE
  data: 0